version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.1
    environment:
      - DEP_VERSION: 0.5.1
    working_directory: /go/src/github.com/budi/training-go
    steps:
      - checkout
      - restore_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/budi/training-go/vendor
      - run:
          name: download-libraries
          command: |
            if [ ! -d /go/src/github.com/budi/training-go/vendor ]; then
                curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o /go/bin/dep
                chmod +x /go/bin/dep
                /go/bin/dep ensure
            fi
      - save_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/budi/training-go/vendor
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
          paths:
            - /tmp/go/cache
      - run:
          name: test
          command: |
            mkdir -p $GOCACHE
            go test -p 6 -race -coverprofile=coverage.out -covermode=atomic -v ./...
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - /tmp/go/cache