version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.1
    working_directory: /go/src/github.com/budi/training-go
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -race -coverprofile=coverage.out -covermode=atomic -v ./...